# Rolling Window parameters
MONTH_LENGTH = 21
INSAMPLE_PERIOD = 6 * MONTH_LENGTH
OUTSAMPLE_PERIOD = MONTH_LENGTH
TOTAL_PERIOD = INSAMPLE_PERIOD + OUTSAMPLE_PERIOD
DAYS_IN_YEAR = 12 * MONTH_LENGTH #for daily data
WEEKS_IN_YEAR = 52 #for weekly data
RESULT_DIRECTORY = 'Results'
INPUT_DIRECTORY = 'Stock_Data'