# Rolling Window parameters
MONTH_LENGTH = 21
INSAMPLE_PERIOD = 6 * MONTH_LENGTH
OUTSAMPLE_PERIOD = 1 * MONTH_LENGTH
TOTAL_PERIOD = INSAMPLE_PERIOD + OUTSAMPLE_PERIOD

# Days and months in a year
DAYS_IN_YEAR = 12 * MONTH_LENGTH #for daily data
WEEKS_IN_YEAR = 52 #for weekly data

# Directories for input and output data
RESULT_DIRECTORY = 'Results'
INPUT_DIRECTORY = 'Stock_Data'

# Parameters used for reading stock_index (filename)
# and stock_index_column_name (column containing index)
STOCK_INDEX = 'S&P500'#'FTSE250'#'CNX50'#'NIFTY500'#'DAX30'#'DOWJONES65'#'FTSE100'#'S&P100'#'NIKKEI225'#'CNX50'#'S&P500'#'DOWJONES65'#
STOCK_INDEX_COLUMN_NAME = 'S&P 500 COMPOSITE - PRICE INDEX'#'FTSE 250 - PRICE INDEX'#'CNX NIFTY (50) - PRICE INDEX'#'NIFTY 500 - PRICE INDEX'#'DAX 30 PERFORMANCE - PRICE INDEX'#'DOW JONES COMPOSITE 65 STOCK AVE - PRICE INDEX'#'FTSE 100 - PRICE INDEX'#'S&P GLOBAL 100 - PRICE INDEX'#'NIKKEI 225 STOCK AVERAGE - PRICE INDEX'#'CNX NIFTY (50) - PRICE INDEX'#'DOW JONES COMPOSITE 65 STOCK AVE - PRICE INDEX'#'NIKKEI 225 STOCK AVERAGE - PRICE INDEX'#'DOW JONES COMPOSITE 65 STOCK AVE - PRICE INDEX'#
INPUT_FILEEXTENSION = '.xlsx'
INPUT_FILENAME = STOCK_INDEX + INPUT_FILEEXTENSION
INDEX_COLUMN_NAME = 'Time'